apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyco
  labels:
    app: dyco-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyco-app
  template:
    metadata:
      labels:
        app: dyco-app
    spec:
      containers:
        - name: dyco-app
          image: docker.pkg.github.com/phagara/dyco/dyco
          envFrom:
            - secretRef:
                name: dyco-secrets
      imagePullSecrets:
        - name: dyco-registry-creds
