apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyco
  labels:
    app: dyco-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyco-app
  template:
    metadata:
      labels:
        app: dyco-app
    spec:
      containers:
        - name: dyco-app
          image: quay.io/dyco/dyco
          ports:
            - containerPort: 9100
          envFrom:
            - secretRef:
                name: dyco-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: dyco-metrics
  labels:
    app: dyco-app
spec:
  type: NodePort
  ports:
    - port: 9100
  selector:
    app: dyco-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dyco-metrics-ingress
  labels:
    app: dyco-app
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
spec:
  rules:
    - http:
        paths:
          - path: /dyco/metrics
            pathType: Prefix
            backend:
              service:
                name: dyco-metrics
                port:
                  number: 9100
