import jsonschema

from .schemas import (
    SCHEMA_CONFIG,
    SCHEMA_HEARTBEAT,
    SCHEMA_INFO_V2,
    SCHEMA_TICKER_TRADING_SUBSCRIBE_RESPONSE,
    SCHEMA_TICKER_TRADING_UPDATE,
)


VALIDATOR_HEARTBEAT = jsonschema.Draft7Validator(SCHEMA_HEARTBEAT)

VALIDATOR_CONFIG = jsonschema.Draft7Validator(SCHEMA_CONFIG)

VALIDATOR_INFO_V2 = jsonschema.Draft7Validator(SCHEMA_INFO_V2)

VALIDATOR_TICKER_TRADING_SUBSCRIBE_RESPONSE = jsonschema.Draft7Validator(
    SCHEMA_TICKER_TRADING_SUBSCRIBE_RESPONSE
)

VALIDATOR_TICKER_TRADING_UPDATE = jsonschema.Draft7Validator(
    SCHEMA_TICKER_TRADING_UPDATE
)
