name: lint-python
on:
  push:
    paths:
      - 'dyco/**.py'
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    paths:
      - 'dyco/**.py'
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          python3 -m pip install -r .github/workflows/black-requirements.txt
          python3 -m black --diff --check dyco
