name: lint-python
on:
  push:
    paths:
      - 'dyco/**.py'
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    paths:
      - 'dyco/**.py'
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: docker://python:3-alpine
        run: |
          # need to install setuptools first, as wrapt's (pylint sub-dep) install scripts depends on it
          pip install -r .github/workflows/setuptools-requirements.txt
          pip install -r .github/workflows/pylint-requirements.txt
          pip install --no-binary :all: --require-hashes -r requirements.txt
          pylint -E dyco
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: docker://python:3-alpine
        run: |
          pip install --no-binary :all: --require-hashes -r .github/workflows/black-requirements.txt
          black --diff --check dyco
