name: lint-on-push
on:
  push:
    paths:
      - 'dyco/**.py'
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    paths:
      - 'dyco/**.py'
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          python3 -m pip install -r .github/workflows/black-requirements.txt
          python3 -m black -t "${BLACK_TARGET_VERSION}" -l "${BLACK_LINE_LENGTH}" --diff --check dyco
        env:
          BLACK_TARGET_VERSION: py38
          BLACK_LINE_LENGTH: 120
