name: lint-python
on:
  push:
    paths:
      - 'dyco/**.py'
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    paths:
      - 'dyco/**.py'
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: |
          # need to install setuptools first, as wrapt's (pylint sub-dep) install scripts depends on it
          python3 -m pip install -r .github/workflows/setuptools-requirements.txt
          python3 -m pip install -r .github/workflows/pylint-requirements.txt
          python3 -m pip install -r requirements.txt
          python3 -m pylint -E dyco
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: |
          python3 -m pip install -r .github/workflows/black-requirements.txt
          python3 -m black --diff --check dyco
