name: publish-release-on-tag
on:
  push:
    tags:
      - 'v*'
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: |
          # need to install setuptools first, as wrapt's (pylint sub-dep) install scripts depends on it
          python3 -m pip install -r .github/workflows/setuptools-requirements.txt
          python3 -m pip install -r .github/workflows/pylint-requirements.txt
          python3 -m pip install -r requirements.txt
          python3 -m pylint -E dyco
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: |
          python3 -m pip install -r .github/workflows/black-requirements.txt
          python3 -m black --diff --check dyco
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: docker run --rm -i hadolint/hadolint:latest-alpine < Dockerfile
  release:
    needs:
      - pylint
      - black
      - hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
  deploy:
    needs: release
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_PLATFORMS: >-
        linux/amd64
        linux/arm/v7
        linux/arm64/v8
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: docker client upgrade
        run: |
          repo="https://download.docker.com/linux/ubuntu"
          curl -fsSL "${repo}/gpg" | sudo apt-key add -
          os="$(lsb_release -cs)"
          sudo add-apt-repository "deb [arch=amd64] ${repo} ${os} stable"
          sudo apt-get update
          sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce-cli
      - name: docker qemu install
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: docker buildx install
        run: |
          docker buildx ls
          docker buildx create --use --name mybuilder
          docker buildx inspect --bootstrap
          docker buildx install
      - name: build image
        run: |
          DYCO_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          docker build --platform "${DOCKER_PLATFORMS// /,}" --tag dyco --build-arg DYCO_VERSION="${DYCO_VERSION}" .
          docker images dyco
      - name: registry login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/dyco

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo ${IMAGE_ID} | tr '[A-Z]' '[a-z]')

          # Strip git tag ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,^refs/tags/,,')

          echo "IMAGE_ID=${IMAGE_ID}"
          echo "VERSION=${VERSION}"

          docker tag dyco "${IMAGE_ID}:${VERSION}"
          for retry in $(seq 5); do docker push "${IMAGE_ID}:${VERSION}" && break || sleep 15; done

          # if this is the highest version git tag, push :latest
          # sleep (hopefully) reduces the chances of push failing with "blob upload unknown" error
          [ "$(git tag | sort -V | tail -n1)" == "${VERSION}" ] \
          && docker tag dyco "${IMAGE_ID}:latest" \
          && sleep 5 \
          && for retry in $(seq 5); do docker push "${IMAGE_ID}:latest" && break || sleep 15; done
